spring:
  datasource:
    url: jdbc:mysql://k7a306.p.ssafy.io:3306/htwm
    username: ssafy
    password: bX,YV8zA=ILub+wO
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA4JCUY2VO4DUQJB5E
      secret-key: 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
    s3:
      bucket: htm-ssafy
    test: hizzzzzzz
